name: CI/CD Docker Pipeline

on:
  push:
    branches:
      - master      
  pull_request:
    branches:
      - master

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_IMAGE_NAME }} # Nama image Docker Anda, misal: useranda/das-stok-akrab-app
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Konteks build (direktori Dockerfile berada). Sesuaikan jika Dockerfile ada di sub-folder.
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: | # Jika Dockerfile Anda butuh build arguments, tambahkan di sini
            VERSION=${{ github.sha }}

  deploy:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add SSH Private Key to the agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Docker Compose
        env:
          # Variabel lingkungan yang dibutuhkan oleh docker-compose
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE_NAME }}:latest
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/ubuntu/dasmanoodanas # Ganti dengan path di server Anda
            docker-compose pull app
            docker-compose up -d --no-deps app
          EOF
  
   