name: CI/CD with Docker Compose

on:
  push:
    branches:
      - master 

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get current date and time for image tag
        id: date
        run: echo "::set-output name=now::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . 
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/das-stok-akrab-app:latest 
            ${{ secrets.DOCKER_USERNAME }}/das-stok-akrab-app:${{ steps.date.outputs.now }} 

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image # Pastikan tahap build & push selesai sebelum deploy
    steps:
      - name: Deploy using SSH and Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          #passphrase: ${{ secrets.SSH_PASSPHRASE }} # Aktifkan baris ini jika SSH key Anda memiliki passphrase
          script: |
            # Pindah ke direktori proyek di server Anda yang berisi docker-compose.yml
            cd /home/ubuntu/dasmanoodanas/ 

            # HENTIKAN DAN HAPUS SEMUA SERVICE DAN VOLUME TERKAIT (PENTING! Data DB akan terhapus jika di volume)
            echo "Stopping and removing existing Docker Compose services and volumes..."
            docker-compose down -v --remove-orphans || true # Menambahkan '|| true' agar tidak gagal jika tidak ada service
            
            # Login ke Docker Hub di server
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # Tarik image terbaru untuk service 'app'
            echo "Pulling latest app image from Docker Hub..."
            docker-compose pull app

            # Jalankan docker-compose kembali dengan image terbaru
            echo "Starting Docker Compose services..."
            docker-compose up -d --build --force-recreate app

            # Membersihkan image Docker yang tidak terpakai
            echo "Pruning unused Docker images..."
            docker image prune -f
