name: CI/CD with Docker Compose

on:
  push:
    branches:
      - master  # Ganti dengan nama branch utama repositori Anda (misalnya: 'master')

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # Menggunakan fetch-depth: 0 untuk memastikan semua riwayat dan tag tersedia,
        # yang berguna jika Anda ingin memberi tag image Docker dengan versi Git.
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get current date and time for image tag
        id: date
        run: echo "::set-output name=now::$(date +'%Y%m%d%H%M%S')"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .  # Menggunakan konteks build dari root repositori
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dasmanoodanas:latest
            ${{ secrets.DOCKER_USERNAME }}/das-stok-akrab:${{ steps.date.outputs.now }}

  deploy_to_server:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image # Pastikan tahap build & push selesai sebelum deploy
    steps:
      - name: Deploy using SSH and Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
          
          
          
        
            cd /home/ubuntu/dasmanoodanas 

            
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            
            docker-compose pull app

            
            
            
            
            docker-compose up -d --force-recreate app

            
            docker image prune -f
